@startuml Classes

' interfaces
interface CommRecvCallback {
    + onRespReceived(head: string, cmd: string, data: string)
    + onCommentReceived(value: string)
    + onReqSent(head: string, cmd: string, data: string)
}

interface GuiInputCallback {
    + onConfirmButtonClicked()
    + onReadyButtonClicked()
    + onKVPChanged(value: double)
    + onMAChanged(value: double)
}

' Builder
class ControllerBuilder {
    - controller : Controller
    + setComm(ins: CommunicationMngr) : ControllerBuilder
    + setImagingMngr(ins: ImagingMngr) : ControllerBuilder
    + setDicomMngr(dicomMngr: DICOMMngr) : ControllerBuilder
    + setGuiMngr(guiMngr: GUIMngr) : ControllerBuilder
    + setPatientInfo(patientInfo: PatientInfo) : ControllerBuilder
    + setDataExport(dataExport : DataExport) : DataExport
    + getResult() : Controller
}

' Controller
class Controller {
    - m_comm : CommunicationMngr
    - m_imagingMngr : ImagingMngr
    - m_dicomMngr : DICOMMngr
    - m_guiMngr : GUIMngr
    - m_patientInfo : PatientInfo
    - m_dataExport : DataExport

    + setComm(ins: CommunicationMngr) : void
    + setImagingMngr(ins: ImagingMngr) : void
    + setDicomMngr(dicomMngr: DICOMMngr) : void
    + setGuiMngr(guiMngr: GUIMngr) : void
    + setPatientInfo(patientInfo: PatientInfo) : void
    + setDataExport(dataExport : DataExport) : void

    ' CommRecvCallback
    # onRespReceived(head: string, cmd: string, data: string)
    # onCommentReceived(value: string)
    # onReqSent(head: string, cmd: string, data: string)
    ' MainPageInputCallback
    # onConfirmButtonClicked()
    # onReadyButtonClicked()
    # onKVPChanged(value: double)
    # onMAChanged(value: double)
}

' Communication manager
class CommMngr {
    - receiver: CommRecvCallback
    + CommMngr(r: CommRecvCallback)
    + OpenEthernet(ip: string, port: port)
    + CloseEthernet()
    + SendCommand(head: string, cmd: string, data: string, bWaitForResponse: bool)
}

' GUI manager
class GUIMngr {
    - mainWindow : MainWindow
    + GUIMngr(mainWindow: MainWindow)
    + ShowMainPage()
}

' Imaging manager
class ImagingMngr {

}

' DICOM manager
class DICOMMngr {

}

' Patient Information
class PatientInfo {

}

' Export resulting data
class DataExport {

}

' Log manager
class LogMngr {

}

' relateions
CommRecvCallback <|.. Controller
CommRecvCallback ..* CommMngr
GuiInputCallback <|.. Controller
GuiInputCallback ..* GUIMngr

@enduml